
GCC=gcc 
GCC_FLAGS=-Wall -ggdb -lpq -I/usr/include/postgresql -lpthread  -lpgport -lpgcommon -L../../../src/common -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -L/usr/lib/mit-krb5 -L/usr/lib/x86_64-linux-gnu/mit-krb5 -L/usr/lib/x86_64-linux-gnu -Wl,--as-needed


all: ps_bgworker

ps_bgworker: main.c
	$(GCC)  -o $@ $^  $(GCC_FLAGS)
clean: 
	rm ps_bgworker
